language: node_js
jobs:
  include:
  - name: Node 10
    node_js: 10
  - name: Node 12
    node_js: 12
  - name: Node 13
    node_js: 13
  - name: Node 14
    node_js: 14
  - name: Node Latest
    node_js: node
    os:
      - windows
      - linux
      - osx
